# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pathToP1: projects/project_1/Project1.StoreApplication
  pathToP1Sln: $(pathToP1)/Project1.StoreApplication.sln
  buildConfiguration: 'Dev'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - $(pathToP1)/*
  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: buildJob
        steps:
#          - task: DotNetCoreCLI@2
#            displayName: 'install .NET 5 sdk'
#            inputs:
#              packageType: 'sdk'
#              version: '5.0.x'
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              command: restore
              restoreSolution: '$(pathToSln)'
#      - job: SonarCloud
#        steps:
  - stage: Publish
    jobs:
      - job: publish
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Publish p1'
            inputs:
             command: 'publish'
             publishWebProjects: true
             projects: $(pathToSln)
             zipAfterPublish: true
          #- task:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure'
            azureSubscription: 'Azure subscription 1(b074c760-5090-4457-b634-bc50e226ed18)'
            appType: 'webApp'
            WebAppName: 'Project1.StoreApplication'
            #deployToSlotOrASE: true
            #ResourceGroupName: ''
            #SlotName: 'production'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
